NIFI-6836 Increased topic list length in ConsumeKafka and added validator
apache/nifi pull request #3885
Opened 2019-11-13 11:53 UTC by bartektartanus

#### Description of PR

NIFI-6836 - this PR increases the topic length limit from 100 to 1000 and also adds validator to warn the user about it. 

I've submitted this issue few days ago and prepared initial version of PR - fixed only for `KafkaConsumer1_0`. This bug is in every Kafka Consumer, from 0_10 to 2_0. I can also make changes in all files, but maybe some refactoring should be done? Some `AbstractKafkaConsumer` with all common properties? Or maybe current approach is intended as you do want to mix code between different versions of Kafka Consumer?

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `master`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on both JDK 8 and JDK 11?

2019-12-10 13:26 UTC, bartektartanus commented
Hello, can we start a discussion about this PR? :D

2019-12-10 15:58 UTC, joewitt commented
@bartektartanus It isn't clear we know what the impact would be in terms of performance and resource usage with a larger number.  That needs testing and description.  We also need this to be on all the relevant Kafka processors like the 2.0 ones as well.

Thanks

2020-01-27 11:20 UTC, bartektartanus commented
So maybe we can leave the limit as is (for now) and only add validator? Because now this processor silently ignores some topics if you specify more than 100.

2020-10-07 12:09 UTC, MikeThomsen requested changes

2020-10-07 12:09 UTC, MikeThomsen commented on nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-1-0-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/ConsumeKafkaRecord_1_0.java
> +            if (input == null || input.trim().isEmpty()) {
`StringUtils.isEmpty` is better here.

2020-10-07 12:09 UTC, MikeThomsen commented on nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-1-0-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/ConsumeKafkaRecord_1_0.java
> +    static final int TOPIC_LIST_MAX_LENGTH = 1000;
I agree with @joewitt that we cannot go up 10x without a serious performance evaluation.

2020-10-07 12:09 UTC, MikeThomsen commented on nifi-nar-bundles/nifi-kafka-bundle/nifi-kafka-1-0-processors/src/main/java/org/apache/nifi/processors/kafka/pubsub/ConsumeKafkaRecord_1_0.java
> +            final int listLength = input.split(",").length;
Better expression is `input.chars().filter(c -> c == ',').count()`

2021-05-11 00:04 UTC, closed without merging