NIFI-7817: Fix ParquetReader instantiation error
apache/nifi pull request #4537
Opened 2020-09-18 01:24 UTC by frankgh

Fixes bug NIFI-7817.

The creation of a ParquetReader is failing due to a null value returned
by:

context.getProperty(ParquetUtils.COMPRESSION_TYPE)

Commit https://github.com/apache/nifi/commit/4f11e3626093d3090f97c0efc5e229d83b6006e4#diff-782335ecee68f6939c3724dba3983d3d
addressed the issue where the property value was being read from the
property parameter instead of the ComponentNode. However, when the
ComponentNode default value is null, the property's default value is
being ignored.

This commit, aims to preserve the original aim of the fix for NIFI-7635,
but it addresses the case where the ComponentNode's default value is
null.

The resolvedValue priority will be resolved in this order:
- configuredValue
- default value from the ComponentNode
- default value from the PropertyDescriptor

2020-09-18 16:31 UTC, markap14 requested changes

2020-09-18 16:31 UTC, markap14 commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/service/StandardConfigurationContext.java
> -        final String resolvedValue = (configuredValue == null) ? resolvedDescriptor.getDefaultValue() : configuredValue;
I don't think this code should be changing at all. We should not use the default value of the given Property Descriptor, but rather use the default value of the one provided by the Controller Service. It appears that the Controller Service is not actually providing a Property Descriptor for this property, which means that it should return `null`. If the Controller Service wants to make use of that property, it needs to expose that property in its `getSupportedPropertyDescriptors` or `getSupportedDynamicPropertyDescriptor` method

2020-09-18 16:33 UTC, markap14 commented
Thanks for the PR @frankgh. It definitely looks like you've done a good bit of work diving in here to understand the flow of all of this logic. But I think the existing implementation is correct - we should not be looking at the default value of the given PropertyDescriptor, but rather making sure the service itself exposes the properties that it's trying to access.

2020-09-18 19:00 UTC, denalex commented
@markap14 -- if you believe the provided patch is not optimal, then the fix indeed will need to happen in `ParquetReader` service component. We are not NiFi contributors (at least not yet :-) so will appreciate someone being assigned to fix the JIRA. Right now reading Parquet files is completely broken due to this issue, as the property cannot even be dynamically assigned:
![Screen Shot 2020-09-18 at 10 28 11 AM](https://user-images.githubusercontent.com/7130388/93635012-643f9f80-f9a6-11ea-946c-7befa1f5d0c2.png)
![Screen Shot 2020-09-18 at 10 28 38 AM](https://user-images.githubusercontent.com/7130388/93635025-699cea00-f9a6-11ea-8766-64b3a5ad2c54.png)

2020-09-19 10:11 UTC, frankgh commented
@markap14 maybe the issue is that for the parquet reader, the compression codec is not required to read parquet files, so the fix should be along the lines of fixing the ParquetReader initialization (making compression codec optional). I agree with @denalex that maybe someone else can look into this issue, as we are not too familiar with the codebase. Thanks!

2020-09-19 12:17 UTC, pvillard31 commented
I reproduced the issue, going to submit a fix for this.

2020-09-19 12:23 UTC, frankgh commented
Thanks, @pvillard31! I will be closing this PR in favor of your fix.

2020-09-19 12:23 UTC, closed without merging