NIFI-6113 Refactoring to remove instance level variable to make it stateless
apache/nifi pull request #4837
Opened 2021-02-23 01:00 UTC by stanislav-antufeev

Refactoring to remove instance level variable to make it stateless.
Fixes bug NIFI-6113, refactoring

2021-02-23 14:22 UTC, stanislav-antufeev commented
Hello Nifi Community. Can someone review and merge my changes to main Nifi branch.
This issue is upvoted and the fix needs to be included into next release.

2021-02-23 22:15 UTC, turcsanyip requested changes
@stanislav-antufeev Thank you for fixing this bug. The code looks good to me (I left two minor comments). I also tested the processor and it works fine. Thanks for the refactoring / code clean-up too, it looks much better now.

Could you please assign the Jira ticket to yourself and also set its status to Patch Available? Thanks

2021-02-23 22:15 UTC, turcsanyip commented on nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/GetHDFSFileInfo.java
>      public void onPropertyModified(PropertyDescriptor descriptor, String oldValue, String newValue) {
This method can be deleted now because it does not do anything just calls the super.

2021-02-23 22:15 UTC, turcsanyip commented on nifi-nar-bundles/nifi-hadoop-bundle/nifi-hdfs-processors/src/main/java/org/apache/nifi/processors/hadoop/GetHDFSFileInfo.java
> +        protected enum Grouping {
As the enclosing class is `package private`, I don't think `protected` really makes sense here. I believe the original was fine. Or do I miss something?

2021-02-24 02:25 UTC, stanislav-antufeev commented
@turcsanyip looks like i don't have enough pemissions on https://issues.apache.org to assign the ticket to me.

2021-02-24 04:11 UTC, pvillard31 commented
@stanislav-antufeev - I added you as a contributor on JIRA and assigned the JIRA to you. You should have enough permissions going forward. Thanks for your contribution.

2021-02-24 12:19 UTC, turcsanyip approved these changes
+1 LGMT
Merging to main.

@stanislav-antufeev Thanks for your contribution.

2021-02-24 12:20 UTC, closed without merging