NIFI-8300 Make non-source processors invalid if scheduled for Primary…
apache/nifi pull request #4913
Opened 2021-03-18 07:02 UTC by s9514171

… Node only

#### Description of PR

Set the processor state to invalid, when the processor has upstream connection and set to "Primary node only"

### For all changes:
- [X] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [X] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [X] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [X] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [X] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [X] Have you verified that the full build is successful on JDK 8?
- [X] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

2021-03-18 14:59 UTC, markap14 requested changes
Thanks for the improvement @s9514171 ! I left a couple of comments inline, as I think we can simplify things a bit and provide a more helpful validation message. Otherwise, all looks good to me.

2021-03-18 14:59 UTC, markap14 commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/StandardProcessorNode.java
> +                        || getInputRequirement() == Requirement.INPUT_ALLOWED && !getIncomingConnections().isEmpty()) {
I think this can be simplified to just: `if (getExecutionNode() == ExecutionNode.PRIMARY && hasIncomingConnection()) {`

2021-03-18 14:59 UTC, markap14 commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/controller/StandardProcessorNode.java
> +                            .explanation("Processor should set to run on all nodes.")
Probably need to provide more details in the explanation. Why should the processor be set to run on all nodes? Perhaps something to the effect of "Processors with incoming connections cannot be scheduled for Primary Node Only."

2021-03-18 15:41 UTC, s9514171 commented
Thanks for your review @markap14 , it looks better now

2021-03-19 14:48 UTC, closed without merging

2021-03-19 14:48 UTC, markap14 commented
Thanks @s9514171 ! Looks good to me too. +1 merged to main!