NIFI-8677 Add custom endpoint suffix for Azure EventHub Processors
apache/nifi pull request #5303
Opened 2021-08-11 07:33 UTC by timeabarna

https://issues.apache.org/jira/browse/NIFI-8677

#### Description of PR

Enables to use special regions including US Government, China, and Germany for Azure EventHub processors.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

2021-11-03 10:15 UTC, timeabarna commented
@jfrazee Hello Joey, can you please check this PR when you have some time? Thanks in advance.

2022-01-27 07:34 UTC, timeabarna commented
@jfrazee Hello Joey, can you please check this PR when you have some time? Thanks in advance.

2022-01-28 16:58 UTC, jfrazee commented
@timeabarna Sorry for taking so long. I'm starting to look at this finally.

2022-01-30 22:06 UTC, jfrazee requested changes

2022-02-04 10:28 UTC, timeabarna commented
Thanks @jfrazee for your help. I've modified the code based on your recommendation.

2022-02-11 18:26 UTC, jfrazee requested changes
@timeabarna Hey, I missed something about how we've changed the endpoint names to remove the leading `.`

That's going to create an upgrade issue for `GetAzureEventHub`. Wanted to see what your thoughts were on whether we revert back to using the leading `.` or live with having to manually intervene for an upgrade.

2022-02-14 08:57 UTC, timeabarna commented
Hello @jfrazee, I've added back the leading '.' to servicebus path, and modified Consume and Put processor code accordingly. Thanks a lot for your help.

2022-02-14 08:59 UTC, timeabarna commented on nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/eventhub/utils/AzureEventHubUtils.java
> +    public static final AllowableValue AZURE_US_GOV_ENDPOINT = new AllowableValue("servicebus.usgovcloudapi.net", "Azure US Government", "Servicebus endpoint for US Government");
I agree with you @jfrazee that option 1 is the better solution, modified the code based on that alternative.

2022-04-04 07:15 UTC, pvillard31 commented
@jfrazee @turcsanyip - what do you think about the current state of this pull request?

2022-04-06 20:41 UTC, jfrazee approved these changes

2022-04-06 20:41 UTC, closed without merging