NIFI-9085 through NIFI-9095 (JUnit refactor of multiple modules)
apache/nifi pull request #5350
Opened 2021-08-26 23:16 UTC by MikeThomsen

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

2021-09-02 16:55 UTC, exceptionfactory requested changes
@MikeThomsen, looking through this quickly, there appear to be a number of places where changes need to be made to use static imports. Thanks!

2021-09-13 16:38 UTC, MikeThomsen commented
@exceptionfactory all of the changes should be in now.

2021-09-13 20:36 UTC, exceptionfactory requested changes
@MikeThomsen, I started going through a detailed review and ran into a number of classes the need to be updated with static imports. I also noticed a number of tests marked with `@Disabled`. I noted a number of occurrences, but I did not go through every file when I started running into large numbers of changed needed.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/kinesis/stream/record/TestKinesisRecordProcessorRaw.java
> +        Assertions.assertNull(verify(kinesisRecord, times(2)).getData());
This should be changed to use static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/kinesis/stream/record/TestKinesisRecordProcessorRecord.java
> +        Assertions.assertNull(verify(kinesisRecord, times(2)).getData());
Change to use static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/kinesis/stream/record/TestKinesisRecordProcessorRecord.java
> +        Assertions.assertNull(verify(kinesisRecord, times(2)).getData());
Change to use static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
> +        Assertions.assertEquals("200",out.getAttribute(PutLambda.AWS_LAMBDA_RESULT_STATUS_CODE), "Status should be equal");
Change to use static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
> +               .startsWith("Could not parse request body into json: Unrecognized token 'badbod': was expecting ('true', 'false' or 'null')"), "exception exception error message should be start with")
Change to use static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
> +    @Disabled
This annotation can be removed since this is an integration test class.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
> +    @Disabled
Annotation can be removed from integration test class.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
> +    @Disabled
Annotation can be removed from integration test class.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/ITPutLambda.java
> +        Assertions.assertEquals(null,out.getAttribute(PutLambda.AWS_LAMBDA_RESULT_STATUS_CODE), "Status should be equal");
Replace with static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/TestPutLambda.java
> +        Assertions.assertEquals("test-function", request.getFunctionName());
Replace with static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/lambda/TestPutLambda.java
> +        Assertions.assertTrue(ff0.isPenalized());
Replace with static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/AbstractS3IT.java
> +            Assertions.fail("Incomplete teardown, subsequent tests might fail");
Replace with static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/AbstractS3IT.java
> +           Assertions.fail("Resource: " + resourceName + " does not exist" + e.getLocalizedMessage());
Replace with static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/AbstractS3IT.java
> +            Assertions.fail("Cannot proceed without File : " + resourceName);
Replace with static imports.

2021-09-13 20:36 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/s3/ITPutS3Object.java
> +        Assertions.assertTrue(runner.setProperty("x-custom-prop", "hello").isValid());
Replace with static imports throughout this class.

2021-09-14 11:48 UTC, MikeThomsen commented
@exceptionfactory good catches. I'll clear them out. I think when I was going through the other PRs more thoroughly this is one I forgot to hit.

2021-09-16 14:48 UTC, MikeThomsen commented
@exceptionfactory should be ready now

2021-09-22 01:33 UTC, exceptionfactory commented
Thanks for the updates on this PR @MikeThomsen. This covers a lot a large number of modules, so it will take some time work through. I noticed the creation of some new integration tests, which makes sense given the existing annotations.

2021-10-04 15:17 UTC, MikeThomsen commented
@exceptionfactory I'll add this to my list to rebase

2021-11-15 14:02 UTC, exceptionfactory requested changes
Getting back to reviewing the JUnit 5 changes, this PR looks close to completion. @MikeThomsen can you rebase and also remove the `System.out.println()` usage from the new Elastisearch integration tests?

2021-11-22 16:16 UTC, MikeThomsen commented
@exceptionfactory should be good to go now

2022-02-28 13:36 UTC, MikeThomsen commented
@exceptionfactory this one should be ready to review as well.

2022-03-08 03:39 UTC, exceptionfactory approved these changes
Thanks for making these updates @MikeThomsen, the latest version looks good! +1 merging.

2022-03-08 03:50 UTC, closed without merging

2022-03-08 14:34 UTC, MikeThomsen commented
thanks!