NIFI-9229 Flow upgrade not possible if a Output Port changes to a funnel
apache/nifi pull request #5402
Opened 2021-09-21 07:34 UTC by timeabarna

https://issues.apache.org/jira/browse/NIFI-9229

#### Description of PR

Fixing bug NIFI-9229

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)? 
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

2021-10-01 08:23 UTC, adenes requested changes
Thanks @timeabarna for the fix. Overall the change looks good to me and works as expected. I only had a few minor comments.

2021-10-01 08:23 UTC, adenes commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
> +                LOG.info("Removing {} from {} not possible at the moment, connection needs to be updated first.", port, group);
Even though this is an info log message at first sight my impression was that I as a user need to "update the connections". Please update this to something like "...not possible at the moment, will try again after updating the connections."

2021-10-01 08:23 UTC, adenes commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
> +                LOG.info("Removing {} from {} not possible at the moment, connection needs to be updated first.", port, group);
same as above

2021-10-01 08:23 UTC, adenes commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
> +        for (final String removedVersionedId : inputPortsRemoved) {
No strong opinion on this, but maybe a log message or a comment would be useful here: "removing the remaining input and output ports".

2021-10-01 08:23 UTC, adenes commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-components/src/main/java/org/apache/nifi/groups/StandardProcessGroup.java
> +                    .filter(component
minor: unnecessary formatting change, please revert

2021-10-01 09:35 UTC, timeabarna commented
Thanks @adenes for your help, I've modified the code based on your recommendations.

2021-10-04 07:14 UTC, adenes approved these changes
Thanks @timeabarna for the follow-up commit, the fix looks good to me. Merging to main.

2021-10-04 07:14 UTC, merged