NIFI-8806 - Refactoring ListenTCP to use netty.
apache/nifi pull request #5493
Opened 2021-10-28 19:02 UTC by thenatog

NIFI-8806 - Cleanup and correcting an issue with batching.

NIFI-8806 - Updated netty sender in test to close after each use.

Thank you for submitting a contribution to Apache NiFi.

Please provide a short description of the PR here:

#### Description of PR

_Enables X functionality; fixes bug NIFI-YYYY._

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [x] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [x] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [x] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [x] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [x] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [x] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

2021-11-09 02:21 UTC, exceptionfactory requested changes
Thanks for making the updates @thenatog! I ran several tests with and without TLS, the changes look good. I noted a couple minor adjustments to the property descriptor ordering in order to preserve the current ordering. Otherwise this looks close to completion.

2021-11-09 02:21 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenTCP.java
> +        descriptors.add(ListenerProperties.NETWORK_INTF_NAME);
This property should be moved to the first position so retain the order from the current version.

2021-11-09 02:21 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenTCP.java
> +        InetAddress hostname = NetworkUtils.getInterfaceAddress(networkInterface);
Recommend renaming to `interfaceAddress`:
```suggestion
        InetAddress interfaceAddress = NetworkUtils.getInterfaceAddress(networkInterface);
```

2021-11-09 02:21 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ListenTCP.java
> +        descriptors.add(SSL_CONTEXT_SERVICE);
The order of these two properties should be reversed to retain the current order.
```suggestion
        descriptors.add(SSL_CONTEXT_SERVICE);
        descriptors.add(CLIENT_AUTH);
```

2021-11-15 17:32 UTC, thenatog commented
Updated as per latest code review

2021-11-16 17:27 UTC, closed without merging