NIFI-9657 Create MoveADLS processor
apache/nifi pull request #5752
Opened 2022-02-08 09:11 UTC by timeabarna

https://issues.apache.org/jira/browse/NIFI-9657

#### Description of PR

Enables moving content into an Azure Data Lake Storage Gen 2.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced 
     in the commit message?

- [ ] Does your PR title start with **NIFI-XXXX** where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically `main`)?

- [ ] Is your initial contribution a single, squashed commit? _Additional commits in response to PR reviewer feedback should be made on this branch and pushed to allow change tracking. Do not `squash` or use `--force` when pushing to allow for clean monitoring of changes._

### For code changes:
- [ ] Have you ensured that the full suite of tests is executed via `mvn -Pcontrib-check clean install` at the root `nifi` folder?
- [ ] Have you written or updated unit tests to verify your changes?
- [ ] Have you verified that the full build is successful on JDK 8?
- [ ] Have you verified that the full build is successful on JDK 11?
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the `LICENSE` file, including the main `LICENSE` file under `nifi-assembly`?
- [ ] If applicable, have you updated the `NOTICE` file, including the main `NOTICE` file found under `nifi-assembly`?
- [ ] If adding new Properties, have you added `.displayName` in addition to .name (programmatic access) for each of the new properties?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI for build issues and submit an update to your PR as soon as possible.

2022-02-08 13:44 UTC, Lehel44 commented
Reviewing

2022-02-09 10:01 UTC, turcsanyip requested changes
@timeabarna Thanks for adding this new feature. I haven't built / tested the processor, just spotted some improvement point in the code. Please find them below in the inline comments.

2022-02-09 10:48 UTC, timeabarna commented
Thanks @turcsanyip for your help, I've modified the code based on your recommendations.

2022-02-16 01:47 UTC, Lehel44 commented on nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/storage/MoveAzureDataLakeStorage.java
> +                        getLogger().warn(warningMessage, new Object[]{flowFile});
You can remove the array creation here and just simply pass the args.

2022-02-16 01:49 UTC, Lehel44 commented on nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/storage/MoveAzureDataLakeStorage.java
> +                if (dlsException.getStatusCode() == 409) {
Do you think the two condition branches can be unified like this?

`if (dlsException.getStatusCode() == 409 && conflictResolution.equals(IGNORE_RESOLUTION) {
...
} else throw dlsException`

2022-02-16 01:53 UTC, Lehel44 commented on nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/storage/MoveAzureDataLakeStorage.java
> +            try {
I think this nested try may be extracted to a separate method to make the code more readable.

2022-02-16 01:59 UTC, Lehel44 commented on nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/storage/MoveAzureDataLakeStorage.java
> +            if (!destinationDirectory.isEmpty() && ! sourceDirectory.isEmpty()) {
Would you please code format this class?

2022-02-16 11:16 UTC, timeabarna commented
Thanks @Lehel44 for your review. I've modified the code based on our discussion.

2022-02-16 16:17 UTC, Lehel44 commented
Thanks @timeabarna LGTM+1

2022-02-22 08:11 UTC, turcsanyip requested changes
@timeabarna I found some more improvement points. Could you please check them?

2022-02-23 06:47 UTC, timeabarna commented on nifi-nar-bundles/nifi-azure-bundle/nifi-azure-processors/src/main/java/org/apache/nifi/processors/azure/AbstractAzureDataLakeStorageProcessor.java
> +            displayName = displayName == null ? DIRECTORY.getDisplayName() : displayName;
Thanks @turcsanyip for your help. I had the same approach first then discovered that sadly DIRECTORY property was not build yet at the constructor time so it is not possible to use as a value at this point.

2022-02-23 07:50 UTC, timeabarna commented
@turcsanyip Thanks for your review, code has been modified based on your findings except the DirectoryValidator.

2022-02-23 15:10 UTC, closed without merging