NIFI-10637 fixing flaky test in TestParseCEF
apache/nifi pull request #6522
Opened 2022-10-13 03:04 UTC by TheGreatRandall

# Summary

[NIFI-10637](https://issues.apache.org/jira/browse/NIFI-10637)
Following the problem in the issue NIFI-10637. I dived deep to the class "ValidateLocale" where the validator has been determined valid or not.
After several printouts and checking log files, we found that the available locales is a deterministic list. 

```
final Locale[] availableLocales = Locale.getAvailableLocales();
```
However, the if condition in this class looks like this:
```
if (availableLocales[0].equals(testLocale)) {
                // Locale matches the "null" locale so it is treated as invalid
                return new ValidationResult.Builder().subject(subject).input(input).valid(false)
                        .explanation(input + " is not a valid locale format.").build();
            }
```
The purpose of this if statement is to determine if the testLocale is empty. However, as I said before, the availableLocales is a given list and the first element is not the zero. So I changed the code to this:

```
if ("".equals(testLocale.toString())) {
                // Locale matches the "null" locale so it is treated as invalid
                return new ValidationResult.Builder().subject(subject).input(input).valid(false)
                        .explanation(input + " is not a valid locale format.").build();
            }

```
By changing this, the if statement can correctly work and the bug has been fixed. It is not flaky anymore and can pass the NonDex's check.
# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [X] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [X] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [X] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [X] Pull Request based on current revision of the `main` branch
- [X] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [X] JDK 8
  - [ ] JDK 11
  - [ ] JDK 17

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

2022-10-14 17:01 UTC, exceptionfactory requested changes
Thanks for the contribution @TheGreatRandall. This looks like a simple improvement. With the removal of `availableLocales[0]`, it looks like the line calling `Locale.getAvailableLocales()` could also be removed. Can you check that and make an update?

2022-10-19 22:17 UTC, TheGreatRandall commented on nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ParseCEF.java
>              final Locale[] availableLocales = Locale.getAvailableLocales();
Thank you for your feedback! I'll update it very soon!

2022-10-23 22:00 UTC, TheGreatRandall commented on nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/ParseCEF.java
>              final Locale[] availableLocales = Locale.getAvailableLocales();
hi, I've removed the variable. Thank you!

2022-10-24 14:49 UTC, exceptionfactory requested changes
Thanks for the updates @TheGreatRandall. Please review the following checkstyle warning:

```
Warning:  src/main/java/org/apache/nifi/processors/standard/ParseCEF.java:[396] (regexp) RegexpSinglelineJava: Line has trailing whitespace.
```

2022-10-31 23:39 UTC, exceptionfactory approved these changes
Removing the empty line cleared the Checkstyle validation, so this looks good. Thanks @TheGreatRandall! +1 merging

2022-10-31 23:43 UTC, closed without merging