NIFI-11985 add ConsumeElasticsearch processor; NIFI-11016 add Query Builder for Elasticsearch processors
apache/nifi pull request #7671
Opened 2023-09-08 06:45 UTC by ChrisSamo632

# Summary

[NIFI-11985](https://issues.apache.org/jira/browse/NIFI-11985) add ConsumeElasticsearch processor, allowing users to track (time) series data in Elasticsearch indices/data streams

[NIFI-11016](https://issues.apache.org/jira/browse/NIFI-11016) add Query Builder for Elasticsearch processors. The new `ConsumeElasticsearch` processor needed a set of query builder-like properties for constructing the necessary Elasticsearch `query`, so extending this to all Elasticsearch processors (where appropriate) seems sensible at the same time.

- Added new `integration-tests` for the Elasticsearch processors to cover the different ways of building Elasticsearch Query DSL
- Updated reading of test data files to be more consistent with the `support/nifi-1.x` branch so that these and future Elasticsearch processor changes will continue to be possible for the NiFi 1.x maintenance branch

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 17

### Licensing

- ~[ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)~
- ~[ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files~

### Documentation

- [x] Documentation formatting appears as expected in rendered files

2023-09-14 19:36 UTC, ChrisSamo632 commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/ConsumeElasticsearch.java
> +                "These parameters will override any matching parameters in the query request body")
Update with NIFI-12063 changes from #7695 if/when accepted

2023-10-09 15:01 UTC, gresockj requested changes
Overall, great work, @ChrisSamo632!  I still need to run the integration tests, and one issue came up during verification, but the general feel of `ConsumeElasticsearch` is very good.  I played around with it a bunch in NiFi and it works well and provides a great deal of flexibility.  I'll submit these comments for now, and let you know if anything comes up during integration tests.

2023-10-09 15:03 UTC, ChrisSamo632 commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/PutElasticsearchRecord.java
> +        input = session.putAllAttributes(input, new HashMap<String, String>() {{
The `<String, String>` is required for Java 8 on the `support/nifi-1.x` branch - while we don't necessarily need to continue pushing to that branch, these changes **should** work fine there, so I wanted to enable that if possible

2023-10-09 15:29 UTC, ChrisSamo632 commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/ElasticsearchRestProcessor.java
> +    String DEFAULT_QUERY_JSON = "{}";
`ElasticsearchRestProcessor` is an `interface`, so this is implicitly `static final` by default (and in fact, I cannot set that explicitly)

2023-10-09 17:42 UTC, gresockj commented
Integration tests look good, so once the above comments are addressed, I think we're good to go.

2023-10-09 18:43 UTC, ChrisSamo632 commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/ConsumeElasticsearch.java
> +        final String trackingRangeValue = getTrackingRangeValueOrDefault(context);
Updated to allow for `stateMap == null` when adding the Query Clause for `ConsumeElasticsearch`

2023-10-09 18:44 UTC, ChrisSamo632 commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/ConsumeElasticsearch.java
> +        @WritesAttribute(attribute = "page.number", description = "The number of the page (request) in which the results were returned that are in the output flowfile"),
Updated (for all affected processors)

2023-10-09 19:45 UTC, gresockj commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/ElasticsearchRestProcessor.java
> +    String DEFAULT_QUERY_JSON = "{}";
Gotcha, missed that.

2023-10-09 20:02 UTC, gresockj commented on nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-restapi-processors/src/main/java/org/apache/nifi/processors/elasticsearch/ConsumeElasticsearch.java
> +        final String trackingRangeValue = getTrackingRangeValueOrDefault(context);
Thanks.  Looks like there's still an issue when verifying with certain unset properties (e.g., Sort):
```
2023-10-09 16:01:21,314 WARN [Verify Processor Config Thread-1] o.a.n.controller.StandardProcessorNode ConsumeElasticsearch[id=14e04756-018b-1000-e816-b1a31e987ad9] Unable to parse Query as JSON
com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: java.util.HashMap["sort"]->java.util.ArrayList[0]->java.util.Collections$SingletonMap["null"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:283)
	at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1366)
	at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1262)
	at com.fasterxml.jackson.databind.ser.impl.FailingSerializer.serialize(FailingSerializer.java:32)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:791)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:808)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:764)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:479)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:318)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4719)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3964)
	at org.apache.nifi.processors.elasticsearch.ElasticsearchRestProcessor.getQuery(ElasticsearchRestProcessor.java:258)
	at org.apache.nifi.processors.elasticsearch.ElasticsearchRestProcessor.verifyAfterIndex(ElasticsearchRestProcessor.java:376)
```

2023-10-10 09:58 UTC, gresockj approved these changes
Thanks for the latest changes -- verification looks good now!

2023-10-10 10:01 UTC, closed without merging