NIFI-12521: Upgrade ca.uhn.hapi dependencies to 2.5.1
apache/nifi pull request #8168
Opened 2023-12-15 22:08 UTC by mark-bathori

# Summary

[NIFI-12521](https://issues.apache.org/jira/browse/NIFI-12521)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

2023-12-16 15:03 UTC, MikeThomsen requested changes
Can you redo this with a variable?

2023-12-16 18:13 UTC, turcsanyip commented
Just a heads-up: 2.5.1 version of the library was compiled to Java 11 so the PR can be applied to the main branch only (nifi 2.x).

2023-12-17 09:39 UTC, mark-bathori commented
Thanks @MikeThomsen for the comment, I've updated the PR.
Thanks @turcsanyip for the additional info.

2024-01-04 10:10 UTC, pvillard31 approved these changes

2024-01-04 10:11 UTC, closed without merging