[NIFI-12504] Remaining views on Summary page
apache/nifi pull request #8174
Opened 2023-12-20 18:06 UTC by rfellows

# Summary

[NIFI-12504](https://issues.apache.org/jira/browse/NIFI-12504)

* process group summary tab
* ellipsify data/headers in table
* input and output port summary tabs
* connections summary tab
* rpg summary tab

2023-12-20 19:41 UTC, mcgilman commented
Will review...

2023-12-21 14:11 UTC, mcgilman requested changes
Thanks for the PR @rfellows!

2023-12-21 14:29 UTC, rfellows commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/summary/ui/common/port-status-table/port-status-table.component.ts
> +                const filterArray: string[] = filter.split('|');
Good catch. I'll come up with a solution

2023-12-22 14:29 UTC, mcgilman approved these changes
Thanks for the updates @rfellows! Will merge once CI completes. +!

2023-12-22 16:08 UTC, rfellows commented
recheck

2023-12-22 19:22 UTC, merged