NIFI-12755 - Upgrade Jetty to 12.0.6
apache/nifi pull request #8374
Opened 2024-02-07 21:20 UTC by pvillard31

# Summary

[NIFI-12755](https://issues.apache.org/jira/browse/NIFI-12755) - Upgrade Jetty to 12.0.6

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

2024-02-07 21:20 UTC, pvillard31 commented
https://github.com/jetty/jetty.project/releases/tag/jetty-12.0.6

2024-02-07 22:06 UTC, exceptionfactory requested changes
Thanks for the upgrade @pvillard31.

Unfortunately, there appears to be some breaking change in 12.0.6 related to the WebSocket components:

```
rror:  org.apache.nifi.websocket.jetty.TestJettyWebSocketServer.testWebSocketConnect -- Time elapsed: 0.261 s <<< ERROR!
java.lang.RuntimeException: Unable to access method public void org.apache.nifi.websocket.jetty.TestJettyWebSocketServer$1.onWebSocketOpen(org.eclipse.jetty.websocket.api.Session)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.toMethodHandle(JettyWebSocketFrameHandlerFactory.java:156)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.createListenerMetadata(JettyWebSocketFrameHandlerFactory.java:170)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.createMetadata(JettyWebSocketFrameHandlerFactory.java:129)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.getMetadata(JettyWebSocketFrameHandlerFactory.java:119)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.newJettyFrameHandler(JettyWebSocketFrameHandlerFactory.java:140)
	at org.eclipse.jetty.websocket.client.internal.JettyClientUpgradeRequest.<init>(JettyClientUpgradeRequest.java:56)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:123)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:103)
	at org.eclipse.jetty.websocket.client.WebSocketClient.connect(WebSocketClient.java:89)
	at org.apache.nifi.websocket.jetty.TestJettyWebSocketServer.testWebSocketConnect(TestJettyWebSocketServer.java:111)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalAccessException: class is not public: org.apache.nifi.websocket.jetty.TestJettyWebSocketServer$1.onWebSocketOpen[Ljava.lang.Object;@5aaaa446/invokeVirtual, from class org.apache.nifi.websocket.jetty.TestJettyWebSocketServer$1 (unnamed module @282f3878)
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:894)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:3987)
	at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:3923)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:4072)
	at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:4065)
	at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:3451)
	at org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory.toMethodHandle(JettyWebSocketFrameHandlerFactory.java:152)
```

2024-02-12 22:05 UTC, exceptionfactory commented
@pvillard31 I tracked down the source of the problem to due visibility of an anonymous class instance used in a test method. The stack trace was related to the visibility of a method within the anonymous class, which makes sense since it was method-local. I moved the test listener out to a public class in the test class and that worked locally as expected. I will plan on merging pending successful automated builds.

2024-02-12 23:41 UTC, exceptionfactory approved these changes

2024-02-12 23:43 UTC, closed without merging