NIFI-12857 Add test for and refactor implementation of QueuePrioritizer
apache/nifi pull request #8466
Opened 2024-03-01 23:37 UTC by EndzeitBegins

# Summary

[NIFI-12857](https://issues.apache.org/jira/browse/NIFI-12857)

Additionally, removed some dead code from `TestStandardFlowFileQueue`.

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [x] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [x] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [x] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [x] Pull Request based on current revision of the `main` branch
- [x] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [x] Build completed using `mvn clean install -P contrib-check`
  - [x] JDK 21

### Licensing

- [x] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [x] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [x] Documentation formatting appears as expected in rendered files

2024-03-26 02:07 UTC, exceptionfactory reviewed
@EndzeitBegins can you rebase this PR from the current main branch? It includes some improvements for the build process that should address the last failure in the Static Analysis workflow step.

2024-03-26 16:58 UTC, EndzeitBegins commented
Of course, just rebased on the last commit of `main`.

2024-05-07 21:25 UTC, exceptionfactory requested changes
@EndzeitBegins Returning to this PR, I noticed a couple stylistic adjustments needed, but with those and one more rebase, this looks close to completion.

2024-05-07 21:25 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/QueuePrioritizer.java
> +        if (claimComparisionResult != 0) return claimComparisionResult;
As a general rule, braces should be used for conditional blocks:
```suggestion
        if (claimComparisionResult != 0) {
            return claimComparisionResult;
        }
```

2024-05-07 21:25 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/QueuePrioritizer.java
> +        if (penaltyComparisonResult != 0) return penaltyComparisonResult;
```suggestion
        if (penaltyComparisonResult != 0) {
            return penaltyComparisonResult;
        }
```

2024-05-07 21:25 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/main/java/org/apache/nifi/controller/queue/QueuePrioritizer.java
> +            if (prioritizerComparisonResult != 0) return prioritizerComparisonResult;
```suggestion
            if (prioritizerComparisonResult != 0) {
                return prioritizerComparisonResult;
            }
```

2024-05-07 21:25 UTC, exceptionfactory commented on nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/queue/QueuePrioritizerTest.java
> +        assertEquals(-1, prioritizer.compare(nonPenalizedFlowFile, longerPenalizedFlowFile));        assertEquals(1, prioritizer.compare(longerPenalizedFlowFile, nonPenalizedFlowFile));
```suggestion
        assertEquals(-1, prioritizer.compare(nonPenalizedFlowFile, longerPenalizedFlowFile));
        assertEquals(1, prioritizer.compare(longerPenalizedFlowFile, nonPenalizedFlowFile));
```

2024-05-09 14:03 UTC, EndzeitBegins commented
Thank you for the review @exceptionfactory. 

I've just rebased the PR on the last commit on `main`, added the missing line break to the test, and added braces to conditional blocks where they were missing. 

I would appreciate another look.

2024-05-09 20:08 UTC, exceptionfactory approved these changes
Thanks @EndzeitBegins! +1 merging

2024-05-09 20:09 UTC, closed without merging