NIFI-12888 In AbstractEmailProcessor recreate email receiver when token expires.
apache/nifi pull request #8494
Opened 2024-03-12 17:08 UTC by tpalfy

# Summary

[NIFI-12888](https://issues.apache.org/jira/browse/NIFI-12888)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

2024-03-18 14:17 UTC, exceptionfactory requested changes
I agree with @dan-s1, the substantive changes are straightforward, but the multiple levels of indentation, particularly with the complex conditionals, make the updated logic more difficult to follow.

2024-03-21 14:16 UTC, tpalfy commented on nifi-nar-bundles/nifi-email-bundle/nifi-email-processors/src/main/java/org/apache/nifi/processors/email/AbstractEmailProcessor.java
> +    }
I usually find it the case that once you understand the complex condition you find the cluttered presentation more appealing. But only after that. When it's cluttered, one needs to look more carefully to understand the relationship between the parts and think through more carefully.

But I think can come up with a compromise and make it more streamlined a bit.

As for doing it in a return statement - I find it much better to return a single variable.

2024-03-26 02:03 UTC, exceptionfactory reviewed
Thanks for making the adjustments @tpalfy, the latest version is much more readable.

@dan-s1 has one remaining comment about the naming convention of the new method, so I will defer to his feedback on that remaining point for now.

2024-03-26 14:45 UTC, dan-s1 commented
@exceptionfactory I think with the latest commit everything seems okay.

2024-03-26 15:18 UTC, pvillard31 approved these changes

2024-03-26 15:23 UTC, closed without merging

2024-05-13 08:00 UTC, AnTu2702 commented
@tpalfy Hey. How are you?

First of all: Thanks for the fix/workaround in NIFI 1.26.
Although things are basically working there, we still don't seem to be through.

The ConsumeIMAP Processor is continuously logging this ERROR...
(although the mailbox can and will be processed successfully using a refreshed token...)

![image](https://github.com/apache/nifi/assets/5054213/d42a733c-42d2-469c-b442-bd0addb61845)

We still have serious doubts to take this into production because of the log being spammed and of course the fact, that we have no clue, what causes this error.

Could you help and double check your fix/workaround?
Thank you in advance...

2024-05-13 15:58 UTC, tpalfy commented
Hi @AnTu2702,

Do you happen to try connecting to an Office365 account?
The issue you mention didn't occur when I was testing but when googled it, it gave me several results users complaining about this when using Office365.

According to one search result this can be caused by clients that are trying to connect too frequently. Can you try lowering the schedule period and see if that helps?
Others suggest checking the OAuth config of Office365.

Couple of links for reference:
https://confluence.atlassian.com/jirakb/imap-fails-with-a3-bad-user-is-authenticated-but-not-connected-error-in-jira-server-integrated-with-office365-665420269.html
https://github.com/mscdex/node-imap/issues/689

2024-05-17 07:38 UTC, AnTu2702 commented
Der alte E-Mail Stack kann abgerissen werden jetzt.
Wir lassen aber den parallelen Betrieb des alten und neuen WhatsApp Postfachs in NIFI vorerst aktiv, bis wieder WhatsApp Emails eintrudeln. Danach schalten wir den Alias um und reißen die alten NIFI Prozesse ab.