[NIFI-13257] codemirror light and dark mode theme
apache/nifi pull request #8855
Opened 2024-05-20 20:19 UTC by scottyaslan

General light mode and dark mode theme support (with proper color contrast ratios) for codemirror v5 editors:

![Kapture 2024-05-20 at 16 11 44](https://github.com/apache/nifi/assets/6797571/a14baf51-78de-4e45-853d-6cbc349857b2)

2024-05-20 21:40 UTC, scottyaslan commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/ui/common/property-table/editors/nf-editor/nf-editor.component.ts
> +            theme: 'nifi',
This adds the `.cm-s-nifi` to any codemirror instance so it will inherit the theme.

2024-05-21 14:44 UTC, rfellows commented
reviewing...

2024-05-21 16:11 UTC, rfellows requested changes

2024-05-21 16:11 UTC, rfellows commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss
There is a flash of what appears to be a text box when opening the editor
![Kapture 2024-05-21 at 12 05 50](https://github.com/apache/nifi/assets/713866/9b94f6f6-d1bf-4ec6-a537-1d656931fecf)

_However, this doesn't seem to be related to this pr specifically. We can track it separately if you like_

2024-05-21 19:57 UTC, scottyaslan commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss
> +    }
updated

2024-05-21 19:58 UTC, scottyaslan commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss
Yes let's file a separate task for this.

2024-05-21 20:43 UTC, rfellows commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss
I logged this JIRA for it: https://issues.apache.org/jira/browse/NIFI-13280

2024-05-21 20:44 UTC, rfellows approved these changes
Looks good to me! Thanks @scottyaslan 👍

2024-05-21 21:25 UTC, scottyaslan commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/assets/styles/_codemirror-theme.scss
https://discuss.codemirror.net/t/help-plz-issue-with-small-white-flickering-input-box-when-codemirror-react-component-first-renders/3942

2024-05-22 11:45 UTC, merged