NIFI-12967: Introducing Back action
apache/nifi pull request #8859
Opened 2024-05-21 15:57 UTC by mcgilman

NIFI-12967:
- Adding support for navigating back to the users previous location in certain circumstances like going to a Controller Service, managing access policies, going to parameters, viewing documentation, opening advanced UIs, and viewing data provenance.
- Cleaning unnecessary instances of postUpdateNavigation.

The scenarios mentioned in the commit message above have a slightly different UX from the existing application. In the old UI, these actions would open in a large modal on top of the current component. When the user was done they could return to where they were by closing the modal. In the new UI, the user currently needs to use their browser back button as the application did not directly offer a back option. This PR introduces that back option but only in the cases identified above. Scenarios outside of this (other links in the application like Referencing Components) are not included here but could be considered in the future as a further improvement over the old UI.

2024-05-21 17:33 UTC, rfellows commented
reviewing...

2024-05-22 17:45 UTC, rfellows requested changes

2024-05-22 17:45 UTC, rfellows commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/app.component.ts
> +                    }
This logic doesn't consider the fact that there might be multiple `backNavigation`'s in the store. If the user is more than one deep and navigates to another page (link from referencing components, main menu, ...) only the last 1 will be popped off and leaving the user with a potentially confusing back navigation option.
Here is an example:

![Kapture 2024-05-22 at 13 35 37](https://github.com/apache/nifi/assets/713866/e08cf74a-7cca-4a40-badc-2385181fb326)

If i had navigated to the referencing process group for the parameter context, the same thing would happen, but the back navigation would show over the canvas which is odd.
<img width="1283" alt="Screenshot 2024-05-22 at 1 38 00 PM" src="https://github.com/apache/nifi/assets/713866/3aca3ec2-0523-47f9-b2cc-54b20b067428">


_Also, the `console.log` should go away_

2024-05-22 18:46 UTC, rfellows commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/controller-services/controller-services.effects.ts
> +                        });
This condition needs to fire regardless of `response.postUpdateNavigationBoundary` existing.
The scenario that demonstrates this is editing a CS then clicking a referencing component. when it asks you to save before navigating, choose Yes. The CS gets saved, but this condition fails and the user is not routed to the referencing component.

2024-05-22 21:11 UTC, rfellows approved these changes
This looks good. Thanks @mcgilman 👍

2024-05-23 22:19 UTC, scottyaslan requested changes
I logged https://issues.apache.org/jira/browse/NIFI-13290 to address the browser history issues I mentioned below. I also found a slight bug that should be fixed here:

![Kapture 2024-05-23 at 16 42 17](https://github.com/apache/nifi/assets/6797571/77f96b04-b247-4f9d-8367-54bac0d73e7e)

2024-05-23 22:22 UTC, scottyaslan commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
>                          });
https://issues.apache.org/jira/browse/NIFI-13290

2024-05-23 22:29 UTC, mcgilman commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/pages/flow-designer/state/flow/flow.effects.ts
>                          });
@scottyaslan Thanks for filing the JIRA. Agreed that is an issue with our dialog close handling when the user navigates forward/back with their browsers. The other scenario looks like a bug in the logic when a new back navigation is pushed that is introduced in this PR. I think simply avoid pushing a duplicate back navigation would address this case. Great idea. Let me prep another commit.

2024-05-24 02:00 UTC, scottyaslan commented on nifi-framework-bundle/nifi-framework/nifi-web/nifi-web-frontend/src/main/nifi/src/app/state/navigation/navigation.reducer.ts
> +            if (draftState.backNavigations.length > 0) {
Looks like there is still a bug in here:

![Kapture 2024-05-23 at 21 59 20](https://github.com/apache/nifi/assets/6797571/bb4db327-47ae-48e0-9704-94b8580442f0)

2024-05-28 19:57 UTC, scottyaslan approved these changes
@mcgilman thank you for this contribution. It is really helpful to be able to quickly return to the component context. One potential improvement would be great if the router state was reapplied during back navigation after a full page refresh but I don't really see that as a common use case.

2024-05-28 19:57 UTC, merged