NIFI-12709 Added ability to get more attributes for zip files as well as created new attributes to get for both tar and zip files.
apache/nifi pull request #9122
Opened 2024-07-29 20:24 UTC by dan-s1

# Summary

[NIFI-12709](https://issues.apache.org/jira/browse/NIFI-12709)

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

2024-08-09 14:54 UTC, exceptionfactory reviewed
Thanks for the improvements @dan-s1. The changes look straightforward in general, I just noted one recommendation to make the code a bit clearer.

One additional note, it looks like it should be possible to update the unit test to check for additional attributes, such as `file.size`, and some of the TAR attributes.

2024-08-09 14:54 UTC, exceptionfactory commented on nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/UnpackContent.java
> +                        String timeAsString = null;
Reusing this variable makes the code difficult to follow. I recommend avoiding reuse and defining specific variables inside the conditional blocks as needed.

2024-08-13 16:26 UTC, exceptionfactory requested changes
Thanks for the updates @dan-s1. This looks closer to completion. In the course of closer review, it seems worth reconsidering the introduction of the new `record` for metadata. Instead of creating a new object for every entry, what do you think about creating separate methods for creating the new `Map` of attributes? Common properties could be passed as arguments, and then the standard `ZipEntry` could set additional values, like file mode and access time, avoiding the intermediate object creation for every entry.

2024-08-13 16:26 UTC, exceptionfactory commented on nifi-extension-bundles/nifi-standard-bundle/nifi-standard-processors/src/main/java/org/apache/nifi/processors/standard/UnpackContent.java
> +        }
Recommend renaming this `record` to `ZipEntryMetadata` as it only applies to a single entry. Also recommend listing each property on its own line for clarity.

2024-08-16 20:49 UTC, exceptionfactory approved these changes
Thanks for making the adjustments @dan-s1, the latest version looks good. +1 merging

2024-08-16 20:58 UTC, closed without merging

2024-08-16 21:04 UTC, dan-s1 commented
@exceptionfactory Thanks for accepting this PR and merging. I just wanted to note I was careful to make sure to instantiate one java.util.Map for creating attributes for both tar and zip entries to be mindful of the issue brought up in [NIFI-13288](https://issues.apache.org/jira/browse/NIFI-13288)

2024-08-16 21:18 UTC, exceptionfactory commented
> @exceptionfactory Thanks for accepting this PR and merging. I just wanted to note I was careful to make sure to instantiate one java.util.Map for creating attributes for both tar and zip entries to be mindful of the issue brought up in [NIFI-13288](https://issues.apache.org/jira/browse/NIFI-13288)

Thanks, I noted that when reviewing the implementation, that's helpful.