NIFI-13951: Add warn policy to dropdown selection
apache/nifi pull request #9478
Opened 2024-10-31 23:53 UTC by sardell

# Summary

[NIFI-13951](https://issues.apache.org/jira/browse/NIFI-13951)

In addition to adding the missing Warn policy level as an option to the enforcement policy select, the default selection is no longer hard coded as `Enforce` but instead reads the value returned from the backend.

cc @pvillard31 

# Tracking

Please complete the following tracking steps prior to pull request creation.

### Issue Tracking

- [ ] [Apache NiFi Jira](https://issues.apache.org/jira/browse/NIFI) issue created

### Pull Request Tracking

- [ ] Pull Request title starts with Apache NiFi Jira issue number, such as `NIFI-00000`
- [ ] Pull Request commit message starts with Apache NiFi Jira issue number, as such `NIFI-00000`

### Pull Request Formatting

- [ ] Pull Request based on current revision of the `main` branch
- [ ] Pull Request refers to a feature branch with one commit containing changes

# Verification

Please indicate the verification steps performed prior to pull request creation.

### Build

- [ ] Build completed using `mvn clean install -P contrib-check`
  - [ ] JDK 21

### Licensing

- [ ] New dependencies are compatible with the [Apache License 2.0](https://apache.org/licenses/LICENSE-2.0) according to the [License Policy](https://www.apache.org/legal/resolved.html)
- [ ] New dependencies are documented in applicable `LICENSE` and `NOTICE` files

### Documentation

- [ ] Documentation formatting appears as expected in rendered files

2024-11-01 11:25 UTC, pvillard31 approved these changes
I tested the fix and everything looks good to me with different rules. I'll let someone more familiar with the UI confirm that code is OK. As far as I'm concerned, I'm a +1.

2024-11-01 14:21 UTC, exceptionfactory requested changes
Although this change itself looks good, I'm going to vote -1 on it for now and close the PR.

The reason is that the `WARN` Enforcement Policy is not implemented at the framework level. For that reason, configuring `WARN` in the UI will not have any effect, leading to user confusion.

This feature needs to be revisited in general, but at minimum, the implications of what a warning should mean need to be reviewed before implementing support in the UI.

Thanks @sardell, this is worth revisiting once the framework changes are evaluated.

2024-11-01 14:36 UTC, exceptionfactory reviewed
Sorry @sardell, I'm retracting my vote after a closer review. I was focused on the enforcement policy references for component validation, missing the visibility in the status section. I defer to others on frontend review.

2024-11-05 00:54 UTC, scottyaslan approved these changes
LGTM. I was able to create a rule and configure it to WARN.

2024-11-05 00:55 UTC, merged